### ISSUE TITLE
Full Hearts not always automatically disappearing

### ISSUE THREAD

**Issue by AstudilloMarillo** [Crendgrim/AutoHUD#99]
I've got the mod set to Reveal health when NotFull. Now, sometimes it seems my health is full because it's showing all of the hearts, but it's not hiding itself. I suspect at such moments the actual numerical value is not 20.0 but somewhere ranging from 19.5 to 19.99. It would be more intuitive if it starts hiding at the moment full hearts are shown in my opinion. 

Or, it might have a completely different cause that I'm not aware of.

**Comment by Crendgrim** [comment]
Hopefully fixed in version 6.6!

**Comment by AstudilloMarillo** [comment]
> Hopefully fixed in version 6.6!

Wonderful, I'll keep an eye out for it!

**Comment by AstudilloMarillo** [comment]
Mmmmh, it seems this is not completely fixed yet. I'm having a hard time replicating this, but what I'm doing is this:
-have Reveal health when NotFull
-run out of hunger so you can't regen
-have feather falling iv boots
-jump off of a 6 block pillar
-it should reveal your hearts since I think the feather falling does something weird like immediately return a certain amount of health after a fall, the hearts should be full (health at 20.0)
-sometimes hearts will not automatically disappear
-repeat if they do disappear

I've not found that when it happened to me just now and I did '/data get entity username' that my health was 19.2.
So, probably the hearts show full when above 19.0, not when above 19.5 like I first suspected.

**Comment by Crendgrim** [comment]
It used to use the logic of rounding down, so 19.2 and 19.8 would both become 19. I changed it to rounding to the nearest heart and thought that fixed it.

When you say the sidebar said you had 20 health, was that after the drop (in other words, when my mod did not register a health change)?

**Comment by AstudilloMarillo** [comment]
> When you say the sidebar said you had 20 health, was that after the drop (in other words, when my mod did not register a health change)?

Yes, that was after the drop. The nbt data tag 'Health' showed 19.2, but the Health scoreboard showed 20. The hearts of the HUD showed all 10 hearts being full, but they did not disappear. 

And just to be clear, I personally think it would be more intuitive if the hearts would disappear (even though technically you'd have 19.2 health) since as a normal survival player, I only have the visual indication of the hearts to go by to determine my health.

**Comment by Crendgrim** [comment]
Ohh, I see. So:
- NBT showed 19.2 health
- scoreboard showed 20 health
- there were 10 hearts rendered
- AutoHUD did not hide the health

Is this correct?
